version: '3.4'

services:
  basketservice:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80; # Be sure about http port exposure
      - Keycloak__Realm=onlineshop
      - Keycloak__AuthServerUrl=http://onlineshop-keycloak.localhost:8080 # It should be configured as https with dns name in production.
      - Keycloak__Audience=BasketService
      - Keycloak__SslRequired=none
      - Keycloak__Resource=OnlineShop_Swagger
      - Keycloak__VerifyTokenAudience=true
      - Keycloak__Credentials__Secret=E8virmFFHzFRpHlqqwK4lQj8mDfHc2XA
      - BasketServiceTokenExchange__Authority=http://onlineshop-keycloak.localhost:8080/realms/onlineshop  # Use container name with http without "/" at the end
      - BasketServiceTokenExchange__RequireHttpsMetadata=false
      - Swagger__Authority=http://onlineshop-keycloak.localhost:8080/realms/onlineshop/protocol
      - Swagger__ClientId=OnlineShop_Swagger
      - Swagger__ClientSecret=E8virmFFHzFRpHlqqwK4lQj8mDfHc2XA
      - CorsOrigins=https://localhost:7235
      - ConnectionStrings__DefaultConnection=Server=onlineshop-sql-server;User Id=sa;Password=myPassw0rd;Initial Catalog=BasketServiceDb;MultipleActiveResultSets=true;TrustServerCertificate=True; # Change sql server DNS name according to module name
      - RemoteServices__CatalogService__Uri=http://onlineshop-catalogservice # Api calls must be against to internal docker network
      - RemoteServices__PaymentService__Uri=http://onlineshop-paymentservice # Api calls must be against to internal docker network
      - RabbitMQ__Host=onlineshop-rabbitmq
      - RabbitMQ__Username=user  
      - RabbitMQ__Password=bitnami
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.crt
      - Kestrel__Certificates__Default__KeyPath=/root/certificate/localhost.key   
    ports:
      - "7202:443"
  catalogservice:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80; # Be sure about http port exposure
      - Keycloak__Realm=onlineshop
      - Keycloak__AuthServerUrl=http://onlineshop-keycloak.localhost:8080
      - Keycloak__Audience=CatalogService
      - Keycloak__SslRequired=none
      - Keycloak__Resource=OnlineShop_Swagger
      - Keycloak__VerifyTokenAudience=true
      - Keycloak__Credentials__Secret=E8virmFFHzFRpHlqqwK4lQj8mDfHc2XA
      - Swagger__Authority=http://onlineshop-keycloak.localhost:8080/realms/onlineshop/protocol
      - Swagger__ClientId=OnlineShop_Swagger
      - Swagger__ClientSecret=E8virmFFHzFRpHlqqwK4lQj8mDfHc2XA
      - CorsOrigins=https://localhost:7235
      - ConnectionStrings__DefaultConnection=Server=onlineshop-sql-server;User Id=sa;Password=myPassw0rd;Initial Catalog=CatalogServiceDb;MultipleActiveResultSets=true;TrustServerCertificate=True; # Change sql server DNS name according to module name
      - RabbitMQ__Host=onlineshop-rabbitmq
      - RabbitMQ__Username=user  
      - RabbitMQ__Password=bitnami
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.crt
      - Kestrel__Certificates__Default__KeyPath=/root/certificate/localhost.key   
    ports:
      - "7008:443"
  fileservice:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80; # Be sure about http port exposure
      - Keycloak__Realm=onlineshop
      - Keycloak__AuthServerUrl=http://onlineshop-keycloak.localhost:8080
      - Keycloak__Audience=FileService
      - Keycloak__SslRequired=none
      - Keycloak__Resource=OnlineShop_Swagger
      - Keycloak__VerifyTokenAudience=true
      - Keycloak__Credentials__Secret=E8virmFFHzFRpHlqqwK4lQj8mDfHc2XA
      - Swagger__Authority=http://onlineshop-keycloak.localhost:8080/realms/onlineshop/protocol
      - Swagger__ClientId=OnlineShop_Swagger
      - Swagger__ClientSecret=E8virmFFHzFRpHlqqwK4lQj8mDfHc2XA
      - CorsOrigins=https://localhost:7235
      - ConnectionStrings__DefaultConnection=Server=onlineshop-sql-server;User Id=sa;Password=myPassw0rd;Initial Catalog=FileServiceDb;MultipleActiveResultSets=true;TrustServerCertificate=True; # Change sql server DNS name according to module name
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.crt
      - Kestrel__Certificates__Default__KeyPath=/root/certificate/localhost.key   
    ports:
      - "7092:443"
  orderservice:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80; # Be sure about http port exposure
      - Keycloak__Realm=onlineshop
      - Keycloak__AuthServerUrl=http://onlineshop-keycloak.localhost:8080
      - Keycloak__Audience=OrderingService
      - Keycloak__SslRequired=none
      - Keycloak__Resource=OnlineShop_Swagger
      - Keycloak__VerifyTokenAudience=true
      - Keycloak__Credentials__Secret=E8virmFFHzFRpHlqqwK4lQj8mDfHc2XA
      - Swagger__Authority=http://onlineshop-keycloak.localhost:8080/realms/onlineshop/protocol
      - Swagger__ClientId=OnlineShop_Swagger
      - Swagger__ClientSecret=E8virmFFHzFRpHlqqwK4lQj8mDfHc2XA
      - CorsOrigins=https://localhost:7235
      - ConnectionStrings__DefaultConnection=Server=onlineshop-sql-server;User Id=sa;Password=myPassw0rd;Initial Catalog=OrderServiceDb;MultipleActiveResultSets=true;TrustServerCertificate=True; # Change sql server DNS name according to module name
      - RabbitMQ__Host=onlineshop-rabbitmq
      - RabbitMQ__Username=user  
      - RabbitMQ__Password=bitnami
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.crt
      - Kestrel__Certificates__Default__KeyPath=/root/certificate/localhost.key   
    ports:
      - "7290:443"

  paymentservice:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80; # Be sure about http port exposure
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.crt
      - Kestrel__Certificates__Default__KeyPath=/root/certificate/localhost.key   
    ports:
      - "7121:443"
  webgateway:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80; # Be sure about http port exposure
      - AuthServer__Authority=http://onlineshop-keycloak.localhost:8080/realms/onlineshop  # Use container name with http without "/" at the end
      - Swagger__Authority=http://onlineshop-keycloak.localhost:8080/realms/onlineshop/protocol
      - Swagger__ClientId=OnlineShop_Swagger
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.crt
      - Kestrel__Certificates__Default__KeyPath=/root/certificate/localhost.key   
    ports:
      - "7235:443"      
   
    
  