version: '3.8'

services:
  keycloak:
    ports:
      - 18080:8080
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_LOG_LEVEL=DEBUG
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=preview
  rabbitmq:
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true   
  sqlserver:
    ports:
      - "1434:1433"
    environment:
      - SA_PASSWORD=myPassw0rd
      - ACCEPT_EULA=Y       