version: '3.8'

services:
  rabbitmq:
    container_name: onlineshop-rabbitmq
    image: bitnami/rabbitmq:latest
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3
    networks:
      - onlineshop-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '5'
          memory: 4096M
        reservations:
          cpus: '1'
          memory: 2048M
  sqlserver:
    container_name: onlineshop-sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - 'sql_data:/var/opt/mssql'
    networks:
      - onlineshop-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S onlineshop-sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '10'
          memory: 8192M
        reservations:
          cpus: '2'
          memory: 8192M          

volumes:
  rabbitmq_data:
    name: onlineshop_rabbitmqdata
    driver: local
  sql_data:
    name: onlineshop_sqldata    
    driver: local
    
networks:
  onlineshop-network:
    name: onlineshop-network
    driver: bridge
#   external: true 