apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileservice
  template:
    metadata: 
      labels:
        app: fileservice
    spec:
      containers:
        - name: fileservice
          image: btrlpuyr/fileservice:latest
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__DefaultConnection
              value: Server=mssql-clusterip-srv,1434;User Id=sa;Password=myPassw0rd;Initial Catalog=FileServiceDb;MultipleActiveResultSets=true;TrustServerCertificate=True; # Change sql server DNS name according to module name
            - name: Keycloak__Realm
              value: "onlineshop"
            - name: Keycloak__AuthServerUrl
              value: "http://keycloak"
            - name: Keycloak__Audience
              value: "FileService"
            - name: Keycloak__SslRequired
              value: "none"
            - name: Keycloak__Resource
              value: "OnlineShop_Swagger"
            - name: Keycloak__VerifyTokenAudience
              value: "true"
            - name: Keycloak__Credentials__Secret
              value: "kBIXR5RCSKdLppZU45ncy3iwCQ8m4A4C"
            - name: Swagger__Authority
              value: "https://keycloak.onlineshop.com/realms/onlineshop/protocol"
            - name: Swagger__ClientId
              value: "OnlineShop_Swagger"
            - name: Swagger__ClientSecret
              value: "kBIXR5RCSKdLppZU45ncy3iwCQ8m4A4C"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://aspire-clusterip-srv:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: fileservice-clusterip-srv
spec:
  type: ClusterIP
  selector: 
    app: fileservice
  ports:
    - name: fileservice
      protocol: TCP
      port: 8080
      targetPort: 8080