apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:25.0.6
        args: ["start", "--cache-stack=kubernetes"]
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: KC_DB
            value: mssql
          - name: KC_DB_URL_DATABASE
            value: master
          - name: KC_DB_URL_HOST
            value: mssql-clusterip-srv
          - name: KC_DB_URL_PORT
            value: "1434"
          - name: KC_DB_SCHEMA
            value: dbo
          - name: KC_DB_URL_PROPERTIES
            value: ";encrypt=false;trustServerCertificate=false"
          - name: KC_DB_USERNAME
            value: sa
          - name: KC_DB_PASSWORD
            value: myPassw0rd
          - name: KC_TRANSACTION_XA_ENABLED
            value: "false"
          - name: "KC_FEATURES"
            value: "preview"
          - name: "KEYCLOAK_ADMIN"
            value: "admin"
          - name: "KEYCLOAK_ADMIN_PASSWORD"
            value: "admin"
          - name: "KC_HEALTH_ENABLED"
            value: "true"
          - name: "KC_HTTP_ENABLED"
            value: "true"
          - name: "KC_HOSTNAME"
            value: "https://keycloak.onlineshop.com"
          - name: "KC_HOSTNAME_ADMIN"
            value: "https://keycloak.onlineshop.com"
          - name: "jgroups.dns.query"
            value: "http://keycloak"
          - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
            value: 'true'
          - name: KC_HOSTNAME_DEBUG
            value: 'true'
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    app: keycloak
