apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderingservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderingservice
  template:
    metadata: 
      labels:
        app: orderingservice
    spec:
      containers:
        - name: orderingservice
          image: btrlpuyr/orderingservice:latest
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80; # Be sure about http port exposure
            - name: ConnectionStrings__DefaultConnection
              value: Server=mssql-clusterip-srv,1434;User Id=sa;Password=myPassw0rd;Initial Catalog=OrderingServiceDb;MultipleActiveResultSets=true;TrustServerCertificate=True; # Change sql server DNS name according to module name
            - name: Keycloak__Realm
              value: "onlineshop"
            - name: Keycloak__AuthServerUrl
              value: "https://keycloak.com"
            - name: Keycloak__Audience
              value: "OrderingService"
            - name: Keycloak__SslRequired
              value: "none"
            - name: Keycloak__Resource
              value: "OnlineShop_Swagger"
            - name: Keycloak__VerifyTokenAudience
              value: "true"
            - name: Keycloak__Credentials__Secret
              value: "UEdCHLNuZgVFtsW5VJEHNQqnZigMlhYH"
            - name: Swagger__Authority
              value: "https://keycloak.com/realms/onlineshop/protocol"
            - name: Swagger__ClientId
              value: "OnlineShop_Swagger"
            - name: Swagger__ClientSecret
              value: "UEdCHLNuZgVFtsW5VJEHNQqnZigMlhYH"
            - name: CorsOrigins
              value: http://webgateway.com
            - name: RabbitMQ__Host
              value: rabbitmq-clusterip-srv
            - name: RabbitMQ__Username
              value: "user"
            - name: RabbitMQ__Password
              value: "bitnami"
---
apiVersion: v1
kind: Service
metadata:
  name: orderingservice-clusterip-srv
spec:
  type: ClusterIP
  selector: 
    app: orderingservice
  ports:
    - name: orderingservice
      protocol: TCP
      port: 80
      targetPort: 80