apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgateway
  template:
    metadata: 
      labels:
        app: webgateway
    spec:
      containers:
        - name: webgateway
          image: btrlpuyr/webgateway:latest
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: Keycloak__Realm
              value: "onlineshop"
            - name: Keycloak__AuthServerUrl
              value: "http://keycloak"
            - name: Keycloak__SslRequired
              value: "none"
            - name: Keycloak__Resource
              value: "OnlineShop_Swagger"
            - name: Keycloak__VerifyTokenAudience
              value: "true"
            - name: Keycloak__Credentials__Secret
              value: "kBIXR5RCSKdLppZU45ncy3iwCQ8m4A4C"
            - name: AuthServer__Authority
              value: "http://keycloak"
            - name: Swagger__Authority
              value: "https://keycloak.com/realms/onlineshop/protocol"
            - name: Swagger__ClientId
              value: "OnlineShop_Swagger"
            - name: Swagger__ClientSecret
              value: "kBIXR5RCSKdLppZU45ncy3iwCQ8m4A4C"
---
apiVersion: v1
kind: Service
metadata:
  name: webgateway-clusterip-srv
spec:
  type: ClusterIP
  selector: 
    app: webgateway
  ports:
    - name: webgateway
      protocol: TCP
      port: 8080
      targetPort: 8080