<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.1" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\BU.OnlineShop.Shared\BU.OnlineShop.Shared.csproj" />
    <ProjectReference Include="..\..\basket\BU.OnlineShop.BasketService.Abstractions\BU.OnlineShop.BasketService.Abstractions.csproj" />
    <ProjectReference Include="..\BU.OnlineShop.OrderingService.Domain.Shared\BU.OnlineShop.OrderingService.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
