<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<UserSecretsId>b52f6e4e-659e-4f4e-835d-c1a9ece5f3ca</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Logs\**" />
	  <Content Remove="Logs\**" />
	  <EmbeddedResource Remove="Logs\**" />
	  <None Remove="Logs\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Keycloak.AuthServices.Authorization" Version="2.5.3" />
		<PackageReference Include="Keycloak.AuthServices.Authentication" Version="2.5.3" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BU.OnlineShop.CatalogService.Database\BU.OnlineShop.CatalogService.Database.csproj" />
	</ItemGroup>

</Project>
