name: Convetinoal Commit

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}