name: Github actions

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint commits
        uses: wagoid/commitlint-github-action@v6

  calculate-version:
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for semantic-release to access all tags and commits
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Calculate next version
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --dry-run | tee result.log
          VERSION=$(grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+' result.log || echo "none")
          echo "Calculated next version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT